name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dotnet 5
      run: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-5.0
        
    - name: Publish with dotnet
      run: dotnet publish BlazorApp.csproj -p:BlazorEnableCompression=false -c Release -o release --nologo
    
    - name: Commit to GitHub pages repo
      run: |
        cd release/wwwroot
        
        git config --local user.email "${{ secrets.EMAIL }}"
        git config --local user.name "XanderCodes"
        
        git add .
        git commit -m "Committed from GitHub Action."

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: master
        repository: XanderCodes/xandercodes.github.io

#     git config --global user.email "${{ secrets.EMAIL }}"
#     git config --global user.name "XanderCodes"
