name: gh-pages

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dotnet 5
      run: sudo apt-get update && sudo apt-get install -y apt-transport-https && sudo apt-get update && sudo apt-get install -y dotnet-sdk-5.0
        
    - name: Publish with dotnet
      run: dotnet publish BlazorApp.csproj -p:BlazorEnableCompression=false -c Release -o release --nologo
    
    - name: Commit to GitHub pages repo
      run: |
        cd release/wwwroot
        
        git add .
        git commit -m "Committed from GitHub Action."
        git branch -M main
                
        git push https://XanderCodes:${{ secrets.PASSWORD }}@github.com/XanderCodes/xandercodes.github.io.git

#     git config --global user.email "${{ secrets.EMAIL }}"
#     git config --global user.name "XanderCodes"
        
    # - name: Commit wwwroot to GitHub Pages
    #   uses: JamesIves/github-pages-deploy-action@3.7.1
    #   with:
    #     ACCESS_TOKEN: ${{ secrets.PAT_TOKEN }}
    #     REPOSITORY_NAME: XanderCodes/xandercodes.github.io
    #     BRANCH: master
    #     FOLDER: release/wwwroot

#     - name: Commit wwwroot to GitHub Pages
#       uses: JamesIves/github-pages-deploy-action@3.7.1
#       with:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         BRANCH: gh-pages
#         FOLDER: release/wwwroot
